language: node_js
node_js:
- node
cache: npm
install:
- npm install
- npm install parcel-bundler
script:
- npm test
- npm run lint
- npm run build
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker build -t jvmartin/starfield:$TRAVIS_COMMIT .
- docker tag jvmartin/starfield:$TRAVIS_COMMIT jvmartin/starfield:$TRAVIS_BRANCH
- docker push jvmartin/starfield
